version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
      - "./data:/var/lib/mysql"

  petclinic:
    image: petclinic
    ports:
      - 8080:8080
    user: "1000"
    links:
      - mysql
    depends_on:
      - mysql
